package com.kissanmitra.domain;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;

import java.time.Instant;

/**
 * Base entity class providing common fields for all domain entities.
 *
 * <p>All entities should extend this class to inherit:
 * <ul>
 *   <li>id - MongoDB document ID</li>
 *   <li>createdAt - Timestamp of entity creation</li>
 *   <li>updatedAt - Timestamp of last update</li>
 * </ul>
 *
 * <p>Note: This class is not annotated with @Document as it's meant to be extended.
 * Child classes should add @Document annotation with their collection name.
 */
@Getter
@Setter
@SuperBuilder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
public abstract class BaseEntity {

    /**
     * MongoDB document ID.
     * Auto-generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * Timestamp when the entity was created.
     * Automatically set by Spring Data MongoDB on save if auditing is enabled.
     */
    @CreatedDate
    private Instant createdAt;

    /**
     * Timestamp when the entity was last updated.
     * Automatically updated by Spring Data MongoDB on save if auditing is enabled.
     */
    @LastModifiedDate
    private Instant updatedAt;
}

